name: sub_notifier_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  flutter_svg: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  talker: ^4.9.2
  talker_flutter: ^4.9.2
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  uuid: ^4.4.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  
  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/services/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Arial
      fonts:
        - asset: fonts/arialmt.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Archivo Black
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
    - family: SN Icons
      fonts:
        - asset: fonts/icons/sn_icons.ttf