name: sub_notifier_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  flutter_svg: ^2.2.0
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^16.0.0
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  slang: ^4.7.3
  slang_flutter: ^4.7.0
  talker: ^4.9.2
  talker_flutter: ^4.9.2
  talker_bloc_logger: ^4.9.2
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  uuid: ^4.4.2
  intl: ^0.19.0
  image_picker: ^1.1.2
  fluttertoast: ^8.2.12
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  flutter_local_notifications: ^19.3.1
  permission_handler: ^12.0.1
  lottie: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  build_runner: ^2.5.4
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4


flutter:
  
  uses-material-design: true

  assets:
    - assets/images/services/
    - assets/icon/
    - assets/lottie/

  fonts:
    - family: Arial
      fonts:
        - asset: fonts/arialmt.ttf
    - family: Archivo Black
      fonts:
        - asset: fonts/ArchivoBlack-Regular.ttf
    - family: SN Icons
      fonts:
        - asset: fonts/icons/sn_icons.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
  macos:
    generate: true
    image_path: "assets/icon/icon.png"